export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_PRODUCTS: "ADD_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
};
